# Generated by Django 5.2.3 on 2026-05-16 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kehadiran",
            name="siswa",
        ),
        migrations.RemoveField(
            model_name="prediksiprestasi",
            name="siswa",
        ),
        migrations.DeleteModel(
            name="DataAkademik",
        ),
        migrations.DeleteModel(
            name="Kehadiran",
        ),
        migrations.DeleteModel(
            name="PrediksiPrestasi",
        ),
        migrations.DeleteModel(
            name="Siswa",
        ),
    ]
