# Generated by Django 5.2.3 on 2026-06-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="guru",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="guru/"),
        ),
    ]
