# Generated by Django 5.2.3 on 2026-05-16 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Siswa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=255)),
                ("nis", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="PrediksiPrestasi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hasil_prediksi",
                    models.CharField(
                        choices=[
                            ("TINGGI", "Prestasi Tinggi"),
                            ("SEDANG", "Prestasi Sedang"),
                            ("RENDAH", "Prestasi Rendah"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "siswa",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prediksi_prestasi",
                        to="academics.siswa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Kehadiran",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("persentase_kehadiran", models.FloatField()),
                ("jumlah_izin", models.PositiveIntegerField(default=0)),
                ("jumlah_sakit", models.PositiveIntegerField(default=0)),
                ("jumlah_alfa", models.PositiveIntegerField(default=0)),
                (
                    "siswa",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kehadiran",
                        to="academics.siswa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DataAkademik",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nilai_tugas", models.FloatField()),
                ("nilai_uts", models.FloatField()),
                ("nilai_uas", models.FloatField()),
                ("rata_rata_semester_sebelumnya", models.FloatField()),
                ("jumlah_mata_pelajaran_lulus", models.PositiveIntegerField()),
                (
                    "siswa",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_akademik",
                        to="academics.siswa",
                    ),
                ),
            ],
        ),
    ]
